import Head from "next/head";
import TagGrid from "components/TagGrid";
import TagRow from "components/TagRow";

const tags = ["Startups", "Tech personalities", "Language learning", "Marketing", "NASA"];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create React Component</title>
        <meta name="description" content="Generated by create react component" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TagGrid items={tags} rows={3} />
      </main>
    </>
  )
}
