import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create React Component</title>
        <meta name="description" content="Generated by create react component" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      </main>
    </>
  )
}
